I create entity payment
scorpion-devv/apiSchoolite pull request #26
Opened 2023-04-01 16:48 UTC by Ramiro925

Crie a entidade de pagamento com os seguintes atributos:
valor, forma de pagamento,data.

2023-04-02 15:19 UTC, MIchelJoaquim requested changes

2023-04-02 15:19 UTC, MIchelJoaquim commented on src/core/entity/payment/payment.ts
> +export class Payment {
Adicione o metodo create e coloca o construtor como privado

2023-04-02 15:19 UTC, MIchelJoaquim commented on src/core/entity/payment/payment.ts
> +    private _value: number;
valor minimo de pagamento deve ser 10

2023-04-03 08:30 UTC, Ramiro925 commented on src/core/entity/payment/payment.ts
> +    private _value: number;
Não consigo entender essa parte, visto que estou a criar uma entidade...

2023-04-10 07:41 UTC, MIchelJoaquim commented on src/core/entity/payment/payment.ts
> +    private _value: number;
Tal como no objeto de valor a entidade também tem um método create que se encarrega da sua criação onde podemos também garantir a sua consistência

2024-01-11 19:23 UTC, merged